---
# tasks file for mariuszczyz.centos-dhcpd

- name: Install DHCP service
  yum:
    name: dhcp
    state: present

- name: Copy custom DHCP configuration files
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
    mode: 0640
    owner: root
    group: root
  notify: restart dhcpd

- name: Start and enable DHCP server
  service:
    name: dhcpd
    state: started
    enabled: yes
