---
# tasks file for mariuszczyz.centos-dhcpd

- name: Install DHCP server package
  package:
    name: dhcp
    state: present

- name: Copy custom DHCP configuration template
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    backup: yes
    mode: 0640
    owner: root
    group: root
  notify: restart dhcpd

- name: Enable DHCP server
  service:
    name: dhcpd
    enabled: yes
